name: Prisma Cloud App Embedded Demo
on: [ push,pull_request ]

jobs:
  prisma_cloud_job:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud steps 
    env:
          PC_USER: ${{ secrets.PC_USER }}
          PC_PASS: ${{ secrets.PC_PASS }}
          PC_CONSOLE: ${{ secrets.PC_CONSOLE }} 
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: twistcli download
        run: curl -s -k -u $PC_USER:$PC_PASS "https://$PC_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli

   
