name: Risky Docker Pipeline

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-api:latest .

    - name: Log in to Nexus Repository
      run: docker login nexusdocker-master-compute.stdeboer.demo.twistlock.com -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}

    - name: Tag Docker Image
      run: docker tag my-api:latest nexusdocker-master-compute.stdeboer.demo.twistlock.com/my-api:latest

    - name: Push Docker Image to Nexus
      run: docker push nexusdocker-master-compute.stdeboer.demo.twistlock.com/my-api:latest
